# Generated by Django 4.2.7 on 2023-11-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_korteks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='JobTitle',
        ),
    ]
