# Generated by Django 4.2.7 on 2023-11-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_korteks_app', '0002_rename_post_jobtitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='post',
            new_name='job_title',
        ),
    ]
