# Generated by Django 4.2.7 on 2023-11-14 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_korteks_app', '0003_rename_employees_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_task_korteks_app.jobtitle'),
        ),
    ]
